// Code generated by "stringer -type Symbol symbol.go"; DO NOT EDIT.

package plural

import "strconv"

const (
	_Symbol_name_0 = "U"
	_Symbol_name_1 = "F"
	_Symbol_name_2 = "I"
	_Symbol_name_3 = "N"
	_Symbol_name_4 = "P"
	_Symbol_name_5 = "T"
	_Symbol_name_6 = "VW"
)

var (
	_Symbol_index_6 = [...]uint8{0, 1, 2}
)

func (i Symbol) String() string {
	switch {
	case i == 0:
		return _Symbol_name_0
	case i == 102:
		return _Symbol_name_1
	case i == 105:
		return _Symbol_name_2
	case i == 110:
		return _Symbol_name_3
	case i == 112:
		return _Symbol_name_4
	case i == 116:
		return _Symbol_name_5
	case 118 <= i && i <= 119:
		i -= 118
		return _Symbol_name_6[_Symbol_index_6[i]:_Symbol_index_6[i+1]]
	default:
		return "Symbol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
